on: pull_request_target

jobs:
#   authorize:
#     environment:
#       ${{ github.event_name == 'pull_request_target' &&
#       github.event.pull_request.head.repo.full_name != github.repository &&
#       'external-collaborators' || 'internal' }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: true

  test:
#    needs: authorize
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external-collaborators' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - run: printenv ABC
        env:
          ABC: ${{ secrets.ABC }}
      - run: |
          echo ${{ github.event.number }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.event.number != '' && 'pr number is not empty' || 'pr number is empty' }}
          echo ${{ github.event.number != '' && join([''], '') || (github.head_ref || github.ref_name) }}
